In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('book.csv', encoding = "ISO-8859-1")

In [3]:
data

Unnamed: 0  User.ID                                         Book.Title  \
0              1   276726                                Classical Mythology   
1              2   276729                                       Clara Callan   
2              3   276729                               Decision in Normandy   
3              4   276736  Flu: The Story of the Great Influenza Pandemic...   
4              5   276737                             The Mummies of Urumchi   
...          ...      ...                                                ...   
9995        9996   162121       American Fried: Adventures of a Happy Eater.   
9996        9997   162121                              Cannibal In Manhattan   
9997        9998   162121                    How to Flirt: A Practical Guide   
9998        9999   162121                                           Twilight   
9999       10000   162129                       Kids Say the Darndest Things   

      Book.Rating  
0               5  
1               3  
2               6  
3               8  
4               6  
...           ...  
9995            7  
9996            9  
9997            7  
9998            8  
9999            6  

[10000 rows x 4 columns]

In [4]:
data1=data.copy()

In [5]:
data1

Unnamed: 0  User.ID                                         Book.Title  \
0              1   276726                                Classical Mythology   
1              2   276729                                       Clara Callan   
2              3   276729                               Decision in Normandy   
3              4   276736  Flu: The Story of the Great Influenza Pandemic...   
4              5   276737                             The Mummies of Urumchi   
...          ...      ...                                                ...   
9995        9996   162121       American Fried: Adventures of a Happy Eater.   
9996        9997   162121                              Cannibal In Manhattan   
9997        9998   162121                    How to Flirt: A Practical Guide   
9998        9999   162121                                           Twilight   
9999       10000   162129                       Kids Say the Darndest Things   

      Book.Rating  
0               5  
1               3  
2               6  
3               8  
4               6  
...           ...  
9995            7  
9996            9  
9997            7  
9998            8  
9999            6  

[10000 rows x 4 columns]

In [6]:
data1=data1.rename({'User.ID':'userid','Book.Title':'booktitle','Book.Rating':'bookrating'},axis=1)

In [7]:
data1

Unnamed: 0  userid                                          booktitle  \
0              1  276726                                Classical Mythology   
1              2  276729                                       Clara Callan   
2              3  276729                               Decision in Normandy   
3              4  276736  Flu: The Story of the Great Influenza Pandemic...   
4              5  276737                             The Mummies of Urumchi   
...          ...     ...                                                ...   
9995        9996  162121       American Fried: Adventures of a Happy Eater.   
9996        9997  162121                              Cannibal In Manhattan   
9997        9998  162121                    How to Flirt: A Practical Guide   
9998        9999  162121                                           Twilight   
9999       10000  162129                       Kids Say the Darndest Things   

      bookrating  
0              5  
1              3  
2              6  
3              8  
4              6  
...          ...  
9995           7  
9996           9  
9997           7  
9998           8  
9999           6  

[10000 rows x 4 columns]

In [8]:
data1.userid.unique()

array([276726, 276729, 276736, ..., 162113, 162121, 162129], dtype=int64)

In [9]:
len(data1.userid.unique())

2182

In [10]:
data2=data1.userid.unique()

In [11]:
data2

array([276726, 276729, 276736, ..., 162113, 162121, 162129], dtype=int64)

In [12]:
userdata=data1.pivot_table(index='userid',
                    columns='booktitle',
                    values='bookrating').reset_index(drop=True)

In [13]:
userdata

booktitle   Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
0                           NaN                                         NaN   
1                           NaN                                         NaN   
2                           NaN                                         NaN   
3                           NaN                                         NaN   
4                           NaN                                         NaN   
...                         ...                                         ...   
2177                        NaN                                         NaN   
2178                        NaN                                         NaN   
2179                        NaN                                         NaN   
2180                        NaN                                         NaN   
2181                        NaN                                         NaN   

booktitle   Repairing PC Drives &amp  '48  \
0                                NaN  NaN   
1                                NaN  NaN   
2                                NaN  NaN   
3                                NaN  NaN   
4                                NaN  NaN   
...                              ...  ...   
2177                             NaN  NaN   
2178                             NaN  NaN   
2179                             NaN  NaN   
2180                             NaN  NaN   
2181                             NaN  NaN   

booktitle  'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
0                                                        NaN                       
1                                                        NaN                       
2                                                        NaN                       
3                                                        NaN                       
4                                                        NaN                       
...                                                      ...                       
2177                                                     NaN                       
2178                                                     NaN                       
2179                                                     NaN                       
2180                                                     NaN                       
2181                                                     NaN                       

booktitle  ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
0                                                        NaN              
1                                                        NaN              
2                                                        NaN              
3                                                        NaN              
4                                                        NaN              
...                                                      ...              
2177                                                     NaN              
2178                                                     NaN              
2179                                                     NaN              
2180                                                     NaN              
2181                                                     NaN              

booktitle  01-01-00: A Novel of the Millennium  \
0                                          NaN   
1                                          NaN   
2                                          NaN   
3                                          NaN   
4                                          NaN   
...                                        ...   
2177                                       NaN   
2178                                       NaN   
2179                                       NaN   
2180                                       NaN   
2181                                       NaN   


In [14]:
userdata.fillna(0, inplace=True)

In [15]:
userdata

booktitle   Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
0                           0.0                                         0.0   
1                           0.0                                         0.0   
2                           0.0                                         0.0   
3                           0.0                                         0.0   
4                           0.0                                         0.0   
...                         ...                                         ...   
2177                        0.0                                         0.0   
2178                        0.0                                         0.0   
2179                        0.0                                         0.0   
2180                        0.0                                         0.0   
2181                        0.0                                         0.0   

booktitle   Repairing PC Drives &amp  '48  \
0                                0.0  0.0   
1                                0.0  0.0   
2                                0.0  0.0   
3                                0.0  0.0   
4                                0.0  0.0   
...                              ...  ...   
2177                             0.0  0.0   
2178                             0.0  0.0   
2179                             0.0  0.0   
2180                             0.0  0.0   
2181                             0.0  0.0   

booktitle  'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
0                                                        0.0                       
1                                                        0.0                       
2                                                        0.0                       
3                                                        0.0                       
4                                                        0.0                       
...                                                      ...                       
2177                                                     0.0                       
2178                                                     0.0                       
2179                                                     0.0                       
2180                                                     0.0                       
2181                                                     0.0                       

booktitle  ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
0                                                        0.0              
1                                                        0.0              
2                                                        0.0              
3                                                        0.0              
4                                                        0.0              
...                                                      ...              
2177                                                     0.0              
2178                                                     0.0              
2179                                                     0.0              
2180                                                     0.0              
2181                                                     0.0              

booktitle  01-01-00: A Novel of the Millennium  \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   
...                                        ...   
2177                                       0.0   
2178                                       0.0   
2179                                       0.0   
2180                                       0.0   
2181                                       0.0   


In [16]:
#Calculating Cosine Similarity between Users
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

In [17]:
user_sim = 1 - pairwise_distances( userdata.values,metric='cosine')

In [18]:
user_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [19]:
user_sim_df = pd.DataFrame(user_sim)

In [22]:
user_sim_df.index = data1.userid.unique()
user_sim_df.columns = data1.userid.unique()

In [23]:
user_sim_df.iloc[0:5, 0:5]

276726  276729  276736  276737  276744
276726     1.0     0.0     0.0     0.0     0.0
276729     0.0     1.0     0.0     0.0     0.0
276736     0.0     0.0     1.0     0.0     0.0
276737     0.0     0.0     0.0     1.0     0.0
276744     0.0     0.0     0.0     0.0     1.0

In [24]:
np.fill_diagonal(user_sim, 0)
user_sim_df.iloc[0:5, 0:5]

276726  276729  276736  276737  276744
276726     0.0     0.0     0.0     0.0     0.0
276729     0.0     0.0     0.0     0.0     0.0
276736     0.0     0.0     0.0     0.0     0.0
276737     0.0     0.0     0.0     0.0     0.0
276744     0.0     0.0     0.0     0.0     0.0

In [25]:
user_sim_df.idxmax(axis=1)[0:5]

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
dtype: int64

In [29]:
data1[(data1['userid']==276729) | (data1['userid']==276726)]

Unnamed: 0  userid             booktitle  bookrating
0           1  276726   Classical Mythology           5
1           2  276729          Clara Callan           3
2           3  276729  Decision in Normandy           6

In [32]:
user_1=data1[data1['userid']==276729]

In [33]:
user_2=data1[data1['userid']==276726]

In [38]:
user_1.booktitle

1            Clara Callan
2    Decision in Normandy
Name: booktitle, dtype: object

In [39]:
user_2.booktitle

0    Classical Mythology
Name: booktitle, dtype: object

In [40]:
pd.merge(user_1,user_2,on='booktitle',how='outer')

Unnamed: 0_x  userid_x             booktitle  bookrating_x  Unnamed: 0_y  \
0           2.0  276729.0          Clara Callan           3.0           NaN   
1           3.0  276729.0  Decision in Normandy           6.0           NaN   
2           NaN       NaN   Classical Mythology           NaN           1.0   

   userid_y  bookrating_y  
0       NaN           NaN  
1       NaN           NaN  
2  276726.0           5.0